-- Enable RLS on all tables and deny all access via Supabase REST API
-- Prisma uses direct connection, so RLS does not affect it

ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Book" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BookChapter" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BookItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CompletionCycle" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyAttendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyProgramCompletion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Evaluation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Group" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GroupBook" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GroupMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GroupSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PositionAdjustment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Program" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Progress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecitationStatus" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ResearchTopic" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SessionAttendance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Surah" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SurahMastery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SurahRecitation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserBook" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserItemProgress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserObjective" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserProgramSettings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserRepresentative" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Verse" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WeeklyObjective" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WeeklyObjectiveCompletion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
